# -*- coding: utf-8 -*-
"""samplesuperstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1voReUJedrr_0mHa9baBfcNGVUkh7hG16
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from scipy import stats

df = pd.read_csv("/content/drive/MyDrive/BDA /samplesuperstore - samplesuperstore.csv")

df.head()

df.info()

df.isnull().sum()

np.mean(df["Sales"])

sales = df.groupby("Category")["Sales"].sum()
sales

plt.bar(sales.index, sales.values)
plt.show()

sns.scatterplot(data=df, x="Sales", y="Profit")
plt.show()

train_data, test_data = train_test_split(df, test_size=0.2)

len(train_data)

len(test_data)

stats.tmean(df["Sales"])